### ISSUE TITLE
What is the difference between Meshgraphnets and MultiMeshGraphnets?

### ISSUE THREAD

**Issue by LearnedVector** [CCSI-Toolset/MGN#12]
Hi, great project! it's unclear to me the difference between meshgraphnets and multimeshgraphnets. 

Can someone add comments on the diff?

**Comment by pn51** [comment]
MultiMeshGraphNets is an extension of MeshGraphNets that allows you to apply message-passing on multiple sets of edges on the same set of nodes.

**Comment by LearnedVector** [comment]
hi @pn51 thanks for the answer! i have another quick question.

Which [partitioning method](https://github.com/CCSI-Toolset/MGN/tree/main/GNN/partitioning) is the one used in the "SCIENTIFIC COMPUTING ALGORITHMS TO LEARN ENHANCED SCALABLE SURROGATES FOR MESH PHYSICS" paper?

specifically the one with ghost nodes.
