### ISSUE TITLE
Adaptive remeshing

### ISSUE THREAD

**Issue by fedebotu** [CCSI-Toolset/MGN#3]
Hi! First of all, thanks a lot for sharing this repository, it has a lot of interesting code.

I would like to ask you whether you implemented some dynamic remeshing strategy as well: I couldn't find it in your code so far, but perhaps I didn't look carefully enough. If not, are you planning to do it?

Thanks in advance :)

**Comment by bbartoldson** [comment]
Hi!

The code does not have a dynamic remesher yet. It's not applicable to the data we're working with at the moment, but we may add it in the future.

Thanks!

Brian

**Comment by fedebotu** [comment]
I see, thanks for your answer! Looking forward for your implementation in the future :)
