### ISSUE TITLE
training and testing dataset

### ISSUE THREAD

**Issue by ylffan** [CCSI-Toolset/MGN#4]
Thanks for sharing this.

May I can why the train and test use the same dataset? (I am not sure if this is intended or if I ran the example incorrectly. Please correct me if I am wrong.)

If that's the case, is it possible to split the dataset into train and test from the already created "CylinderFlowDatasetNP" object? Or they just have to be loaded separately from scratch.

**Comment by pn51** [comment]
The cylinder flow script using the CylinderFlowDatasetNP class and included simulation data was only intended as an example of how to run the code; it written to verify that the model can train and overfit to that simulation. As written, the class uses the entire simulation, so you would have to create another object to split the dataset.

**Comment by ylffan** [comment]
@pn51 Thanks for the clarification!
