### ISSUE TITLE
Version requirements

### ISSUE THREAD

**Issue by pholur** [CCSI-Toolset/MGN#9]
Is it possible to get versioning on the requirements listed in the README? It's been difficult to setup the environment.
Thanks!

**Comment by lbianchi-lbl** [comment]
@pholur Thanks for the suggestion, I think this would be helpful and useful in general.

@pn51 it should be enough to run `pip freeze > requirements.txt` in any environment that's known to be working. Do you think you could open a PR with this?

**Comment by pn51** [comment]
@pholur We'll have this included in our next release.
